print("="*45)
print("SERVIDORVERDE - MENÚ PRINCIPAL")
print("="*45)
print("  1. Ver puntuación de sostenibilidad")
print("  2. Ver ranking de zonas")
print("  3. Calcular emisiones de carbono")
print("  4. Salir")
print("="*45)
print("Selecciona una opción: ")
